# Generated by Django 3.2.3 on 2021-06-01 16:46

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Structure",
            fields=[
                ("id", models.BigAutoField(primary_key=True)),
                ("geom", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ("name", models.CharField(max_length=255)),
                ("label", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Building",
            fields=[
                (
                    "structure_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="qdmtkdemo.structure",
                    ),
                ),
                ("stories_count", models.IntegerField()),
            ],
            bases=("qdmtkdemo.structure",),
        ),
    ]
