# Generated by Django 3.2.5 on 2021-07-08 16:37

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app_b", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LandLot",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app_b.owner",
                    ),
                ),
            ],
        ),
    ]
