# Generated by Django 3.2.3 on 2021-06-01 17:31

from django.db import migrations


def seed_data(apps, schema_editor):
    Structure = apps.get_model("core", "Structure")
    Building = apps.get_model("core", "Building")

    Structure.objects.create(
        name="your house",
        geom="SRID=4326;POINT(6.16 46.21)",
    )
    Building.objects.create(
        name="my house",
        stories_count=4,
        geom="SRID=4326;POINT(6.14 46.20)",
    )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [migrations.RunPython(seed_data)]
