# Generated by Django 3.2.5 on 2021-07-08 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_a", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Building",
            fields=[
                (
                    "structure_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="app_a.structure",
                    ),
                ),
                ("stories_count", models.IntegerField()),
            ],
            bases=("app_a.structure",),
        ),
    ]
