"""geo

Revision ID: b65334d397fa
Revises: 1713e7a9eb2b
Create Date: 2021-05-31 19:59:55.278274

"""
from alembic import op
from sqlalchemy.sql import func, select

# from . import functions  # NOQA
# from . import types  # NOQA

# from geoalchemy2.functions import AddGeometryColumn


# revision identifiers, used by Alembic.
revision = "b65334d397fa"
down_revision = "1713e7a9eb2b"
branch_labels = None
depends_on = None


def upgrade():

    # Seems like management=True is ignored (see https://geoalchemy-2.readthedocs.io/en/latest/types.html#geoalchemy2.types.Geometry)
    # op.add_column('structures', sa.Column('geom', qdatamodel.utils.NonExtendedGeometry(geometry_type='POINT', srid=4326, management=True, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True))

    stmt = select([func.AddGeometryColumn("structures", "geom", 4326, "POINT", 2)])
    stmt = stmt.execution_options(autocommit=True)
    op.execute(stmt)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("structures", "geom")
    # ### end Alembic commands ###
