"""test

Revision ID: 1713e7a9eb2b
Revises:
Create Date: 2021-05-31 19:15:03.403986

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "1713e7a9eb2b"
down_revision = None
branch_labels = ["0.0.0"]
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "structures",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "buildings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("stories_count", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["id"],
            ["structures.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "monuments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tripadvisor_rating", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["id"],
            ["structures.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("monuments")
    op.drop_table("buildings")
    op.drop_table("structures")
    # ### end Alembic commands ###
